### ISSUE TITLE
Pinout for E18-MS1PA1-PCB flashing

### ISSUE THREAD

**Issue by AS137430** [kianusch/flashPiCC#1]
Hi @kianusch 
Can you confirm the pinout for flashing E18-MS1PA1-PCB ?

```
E18                Cable                    Rpi
 Pin 1(GND)    Pin 1(GND)       GND (e.g.PIN9) 
 Pin 24(RST)   Pin 7 (RST)         GPIO22 (PIN31)
 Pin 3(P2.2)    Pin 3 (DC)           GPIO0 (PIN11)
 Pin 4(P2.1)    Pin 4 (DD)           GPIO2 (PIN13)
```

**Comment by kianusch** [comment]
You are right ... the raspberry-side is mixed up (DC vs. DD) sorry.
So ether swap the cable on the raspberry-side  or change the source code to ... 

// DEFINES
#define RESET 22
#define DC 0
#define DD 2

You can actualy use any three free PINs on the raspberry - and change the code to your needs.

(I'll change the README). Thanks.
